api_user:
    type:     rest
    resource: "@ApiManagerBundle/Resources/config/routing.yml"
    prefix:   /api

api_consultant:
    type:     rest
    resource: "@ApiManagerBundle/Resources/config/routing/consultant.yml"
    prefix:   /api

api_commercial:
    type:     rest
    resource: "@ApiManagerBundle/Resources/config/routing/commercial.yml"
    prefix:   /api


app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }